name: starter
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py36_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1b=h1de35cc_0
  - pip=10.0.1=py36_0
  - python=3.6.8=haf84260_0
  - readline=7.0=h1de35cc_5
  - setuptools=40.8.0=py36_0
  - sqlite=3.26.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.7.0
    - astor==0.7.1
    - gast==0.2.2
    - grpcio==1.19.0
    - h5py==2.9.0
    - keras==2.2.4
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - markdown==3.0.1
    - mock==2.0.0
    - numpy==1.16.2
    - pandas==0.24.1
    - pbr==5.1.3
    - protobuf==3.7.0
    - python-dateutil==2.8.0
    - pytz==2018.9
    - pyyaml==3.13
    - scikit-learn==0.20.3
    - scipy==1.2.1
    - six==1.12.0
    - tensorboard==1.13.0
    - tensorflow==1.13.1
    - tensorflow-estimator==1.13.0
    - termcolor==1.1.0
    - werkzeug==0.14.1
